drop database if exists DBVACINACAO ;
CREATE DATABASE DBVACINACAO;
USE DBVACINACAO;

CREATE TABLE VACINA (
	IDVACINA INT AUTO_INCREMENT PRIMARY KEY NOT NULL 
    , NOME VARCHAR(100) NOT NULL UNIQUE
    , INICIO_PESQUISA DATE NOT NULL
    , PESQUISADOR VARCHAR(100) NOT NULL
    , ESTAGIO VARCHAR(100) NOT NULL
);

CREATE TABLE PESSOA (
	IDPESSOA INT AUTO_INCREMENT PRIMARY KEY NOT NULL 
    , CPF VARCHAR(11) NOT NULL UNIQUE
    , NOME VARCHAR (100) NOT NULL
    , NASCIMENTO DATE NOT NULL
    , SEXO char(1)
	, CATEGORIA varchar(13) not null
);

CREATE TABLE APLICACAO (
	IDAPLICACAO INT AUTO_INCREMENT PRIMARY KEY NOT NULL
    , DT_APLICACAO DATE NOT NULL
    , IDVACINA INT NOT NULL
    , IDPESSOA INT NOT NULL
    , CONSTRAINT FK_APLICACAO_VACINA FOREIGN KEY (IDVACINA) REFERENCES VACINA (IDVACINA)
    , CONSTRAINT FK_APLICACAO_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA)
);

CREATE TABLE AVALIACAO_APLICACAO (
	IDAVALIACAO_APLICACAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , DT_AVALIACAO DATE NOT NULL
    , NOTA INT NOT NULL
    , DESCRICAO VARCHAR(500) NOT NULL
    , IDAPLICACAO INT NOT NULL
    , CONSTRAINT FK_AVALIACAO_APLICACAO_APLICACAO FOREIGN KEY (IDAPLICACAO) REFERENCES APLICACAO (IDAPLICACAO)
);

CREATE TABLE PESQUISADOR_VACINA (
	IDPESQUISADOR INT NOT NULL 
    , IDVACINA INT NOT NULL
    , PRIMARY KEY (IDPESQUISADOR ,IDVACINA)
    , CONSTRAINT FK_PESQUISADOR_PESSOA FOREIGN KEY (IDPESQUISADOR) REFERENCES PESSOA (IDPESSOA)
    , CONSTRAINT FK_PESQUISADOR_VACINA FOREIGN KEY (IDVACINA) REFERENCES VACINA (IDVACINA)
);


/*
-- TABELA RELACIONAL
CREATE TABLE AVALIACAO_DESCRICAO(
	IDAVALIACAO INT
    ,IDDESCRICAO INT
    ,PRIMARY KEY (IDAVALIACAO, IDDESCRICAO)
    , CONSTRAINT FK_AVALIACAO_DESCRICAO_AVALIACAO FOREIGN KEY (IDAVALIACAO) REFERENCES AVALIACAO_APLICACAO (IDAVALIACAO_APLICACAO)
    , CONSTRAINT FK_AVALIACAO_DESCRICAO_DESCRICAO FOREIGN KEY (IDDESCRICAO) REFERENCES DESCRICAO (IDDESCRICAO)
);

-- TABELA COM ITENS PRE-INSERIDOS
CREATE TABLE DESCRICAO(
	IDDESCRICAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , DESCRICAO VARCHAR(100) NOT NULL
    , DETALHES VARCHAR(100) NOT NULL
);

INSERT INTO AVALIACAO_DESCRICAO
	(IDDESCRICAO, DESCRICAO)
VALUES 
	(1,'OUTRO')
	,(2,'FEBRE')
    ,(3,'VERMELHIDÃO NO LOCAL DE APLICAÇÃO')
    ,(4,'REAÇÃO ALERGICA')
    ,(5,'CALAFRIO')
    ,(6,'DOR DE CABEÇA')
    ,(7,'DOR NO LOCAL DE APLICAÇÃO')
    ,(8,'NÁUSEA')
    ,(9,'DIARREIA')
    ,(10,'CANSAÇO')
;
*/