USE DBVACINACAO;



DELIMITER $$
CREATE TRIGGER TG_APLICACAO BEFORE INSERT ON APLICACAO FOR EACH ROW
BEGIN
	
    DECLARE var_DT_INICIO_PESQUISA DATE;
    SELECT INICIO_PESQUISA FROM VACINA WHERE IDVACINA = NEW.IDVACINA INTO var_DT_INICIO_PESQUISA;
    
    IF (DATEDIFF(NEW.DT_APLICACAO ,var_DT_INICIO_PESQUISA) < 0)
		THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERRO DATA INCORRETA: A A DATA DE APLICACAO NÃO PODE SER ANTERIOR DA DATA DE INICIO DA PESQUISA.';
        
        END IF;

END$$

CREATE TRIGGER TG_PESQUISADOR_VACINA BEFORE INSERT ON PESQUISADOR_VACINA FOR EACH ROW
BEGIN
	
    IF (SELECT CATEGORIA FROM PESSOA WHERE IDPESSOA = NEW.IDPESQUISADOR) <> 'PESQUISADOR'
		THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERRO: SOMENTE PESQUISADOR PODE TER OCORRENCIA DO ID EM PESQUISA';
    END IF;
	
END$$


DELIMITER ;

INSERT INTO PESQUISADOR_VACINA
(
	IDPESQUISADOR
    , IDVACINA

)
VALUE (
	1
    ,1
)
;


-- SELECT COUNT(NOME) FROM VACINA WHERE NOME='ALPHA';